version: '3'
services:
  superset:
    image: amancevice/superset:latest
    environment:
      - SUPERSET_CONFIG_PATH=/etc/superset/superset_config.py
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
    ports:
      - "8088:8088"